wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.20
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.6.9
    t:
      1:
      - 2
      - 3
      4: 3.6.9
      5: 0.10.20
      8:
      - 1
      - 5
